server:
  port: 10001
  tomcat:
    uri-encoding: UTF-8
  session:
    timeout: 3600
spring:
  messages:
    encoding: UTF-8
  aop:
    auto: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #   测试环境
    url: jdbc:mysql://localhost:3306/erleihu?useUniCode=true&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimeZone=GMT
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 10
      #最大值
      maxActive: 100
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      #      maxWait: 6
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      #      timeBetweenEvictionRunsMillis: 6
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      #      minEvictableIdleTimeMillis: 30
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      keepAlive: true
      poolPreparedStatements: true
      removeAbandoned: false
      removeAbandonedTimeout: 1800
      #      removeAbandonedTimeout: 18
      logAbandoned: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，
      #'wall'用于防火墙，SpringBoot中没有log4j，我改成了log4j2
      filters: stat,wall,log4j2
      #最大PSCache连接
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # 配置StatFilter
      web-stat-filter:
        #默认为false，设置为true启动
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #允许那些ip
        allow: 127.0.0.1,39.170.50.91
        login-username: lgyfpt_api
        login-password: js@lgyfpt.com
        #禁止那些ip
        deny: 192.168.1.102
        #是否可以重置
        reset-enable: true
        #启用
        enabled: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 30000

mybatis:
  type-aliases-package: com.lgyf.demo.bean
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:sqlMapConfig.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.security: INFO
    mapper: debug
  file:
    path: D://java